### ISSUE TITLE
Other Components of the Dataset Needed

### ISSUE THREAD

**Issue by mbachewi** [UW-Biol419-Wi2016/Melanophore-RNA-Seq-Project#1]
If we have chromosome position of each of the identified genes, that will be necessary for chromosome mapping. We also need the read count data to undertake the normalization and differential gene expression analyses that they suggest. (Unless that's what the fpkm values already are). A summary table of how many reads were assigned vs unassigned could also be useful.

**Comment by lsaund11** [comment]
The FPKM values are a proxy for read counts, since we cannot calculate actual read counts. My guess is that we can get the chromosome location data from ensembl or UCSC genome browser. And I can pull the assigned vs. unassigned reads off of the tophat reports.
